openapi: 3.0.0
info:
  title: Beauty Salon API
  version: 1.0.0
paths:
  /appointments:
    get:
      summary: Retrieve all appointments
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    client_name:
                      type: string
                    appointment_time:
                      type: string
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:YOUR_ACCOUNT_ID:function:getAppointments/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
